import { defineConfig } from 'orval'

export default defineConfig({
  rostra: {
    input: '../../server/target/openapi.json', // generated by SmallRye
    output: {
      target: './src/kernel/api/generated.ts',
      client: 'react-query',
      mode: 'tags-split',
      override: {
        mutator: {
          path: './src/kernel/api/fetcher.ts',
          name: 'apiFetcher',
        },
      },
    },
  },
})
